"""revised_table

Revision ID: 1693bd6e5777
Revises: 93b8e0ec3373
Create Date: 2025-07-22 06:53:41.976486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1693bd6e5777'
down_revision: Union[str, None] = '93b8e0ec3373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chatbot_llm_model_name', table_name='chatbot')
    op.drop_column('chatbot', 'llm_model_name')
    op.add_column('organizations', sa.Column('chat_model_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'chat_model_name')
    op.add_column('chatbot', sa.Column('llm_model_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.create_index('ix_chatbot_llm_model_name', 'chatbot', ['llm_model_name'], unique=False)
    # ### end Alembic commands ###
